### PR TITLE
Tell Github to go away when it wants to commit .atom-build config file

### PR DESCRIPTION
**Pull request by ghost**
why haven't they fixed this yet jesus

### CODE REVIEW

**Comment by ghost** [comment]
literally unplayable

**Comment by CrAzYPiLoT-SS13** [comment]
Because we don't use Atom for Rust (ew). Just use IntelliJ IDEA like a normal person :^)

**Comment by PJB3005** [comment]
> Because we don't use Atom for Rust (ew). Just use IntelliJ IDEA like a normal person :^)

I do.

> Also what the literal fuck did you do, this isn't how it works.

???

**Comment by ghost** [comment]
> Also what the literal fuck did you do, this isn't how it works.

????????????????

**Comment by ghost** [comment]
>Also what the literal fuck did you do, this isn't how it works.

that's how it works, @CrAzYPiLoT-SS13
you can create .atom-build.yml, .atom-build.json (maybe .atom-build.txt), and Atom will recognize all of those.
So he put mask * in the end of filename to be sure GIT will ignore ALL of them

Edit(https://github.com/NanotrasenInc/YASSS13RTWCF/commit/f7ba875ff08c2ebe25c2aafee452d9e7016af63e): **oh shiete you madman what have you done**

**Comment by CrAzYPiLoT-SS13** [comment]
Oh. I've never seen it done as .*. FML

**Pull request merged**
